### ISSUE TITLE
PF 6.3 Compatibility

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions.github.com#569]
**Tasks:**
- [ ] Remove Commons Lang
- [x] WidgetBuilder calls changed to just init().
- [x] Remove the JS functions for PrimeFacesExt.getFacesResource() and replace with PrimeFaces.resources.getFacesResource().
- [x] Remove the JS functions for PrimeFacesExt.escapeHtml and replace with PrimeFaces.escapeHtml in GitHub component..
- [x] Find JS widgets where the BaseWidget callBehavior can be used.
- [x] Fix compiler failures like PrimeRequestContext.
- [x] Update JAR versions of GSON.
- [ ] Switch components to use "Base" pattern like PF to just contain all their properties
- [x] Check for CoreRenderer shouldDecode(), renderRequired(), and renderAccessibilityAttributes() usage
- [x] RenderValidationMetadata for CodeMirror, CKEditor, TimePicker etc?
- [x] PF SavedState instead of SavedEditableState in PFE (class looks identical)

This will be my running list of issues to make sure I don't forget when we upgrade to PF 6.3.

**Comment by melloware** [comment]
Yep this is correct.  I was leaving PFE 6.3.-SNAPSHOT on PF 6.2 for now so hopefully we can figure out the DeferredRenderer issue and cut a PFE 6.2.5 Release.  Unless we discover its a PF issue.   Did you create a PrimeFaces Test project showing the issue so we can submit to PF using only PF components?

After that my plan was to upgrade PFE to 6.3-SNAPSHOT and fix the incompatibilities.

**Comment by jxmai** [comment]
> Did you create a PrimeFaces Test project showing the issue so we can submit to PF using only PF components?

Not yet. Just a discussion: based on the fact it seems like we may need extension layout so the sample probably won't be PF components only.

---

A few notes before looking into the implementation:

1. compare TabView with layout as the parent container

2. compare MOVE_SCRIPT_TO_BOTTOM with non MOVE_SCRIPT_TO_BOTTOM

3. compare PF 6.1 with PF 6.2

**Comment by melloware** [comment]
These are great debugging steps.

**Comment by tandraschko** [comment]
Just my thoughts: if no-one of you runs PF6.3-SNAPSHOT in production, i would wait with the migration until ~2 weeks before the PF6.3-RC1

**Comment by jxmai** [comment]
That's fine. I am not using PF 6.3 SNAPSHOT in production. Let's follow the schedule then unless there are some other requests :smile:

**Comment by mdzaebel** [comment]
I use PFE and a PF 6.2.9 fix. However, as long as this issue is not closed, I have no chance to run the PF fix. I would recommend, that incompatible changes are simultaneous fixed in important libs like PFE too.

**Comment by melloware** [comment]
Hmm I use PFE 6.2.10 with PF 6.2.10 without issue?   If you are having the above issue are you sure you don't accidentally have a 6.3-SNAPSHOT of PF running?  That would cause this issue.

Right now we keep our versions in line where 6.2 is compatible with 6.2.X and not 6.3.    We plan on updating to 6.3 once PF 6.3 goes RC1.

**Comment by mdzaebel** [comment]
You are completely right. Thanks for clarification.

**Comment by tandraschko** [comment]
I would personally try to get rid of commons-lang - most of the times only same "language shortcurts" are used and not worth to use it.

**Comment by melloware** [comment]
Agreed let me update since PF core has "isValueBlank" which is mostly what is used.

**Comment by cnsgithub** [comment]
Additional task:

- [ ] For PF 6.3 use PrimeFaces.escapeHTML, remove PrimeFacesExt.escapeHTML, see https://github.com/primefaces-extensions/core/pull/61

**Comment by melloware** [comment]
OK I just checked in all the changes I have so far for 6.3 compatibility and checked the items off the list above.  Still have a few to go.

**Comment by melloware** [comment]
I have completed all tasks except 2 which I created two other tickets for because they are larger efforts and they are not required to make it work with PF  6.3.
https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/634
https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/635
